name: Generate Sitemap

on:
  push:
    branches:
      - main  # change if your branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate sitemap.xml
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
        echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml

        # loop through all HTML files except CNAME and README
        for file in $(find . -name "*.html" ! -name "README.html" ! -name "index.html"); do
          filename=$(basename $file .html)
          echo "  <url>" >> sitemap.xml
          echo "    <loc>https://tools.skill2job.site/$filename</loc>" >> sitemap.xml
          echo "    <priority>0.8</priority>" >> sitemap.xml
          echo "  </url>" >> sitemap.xml
        done

        # Add homepage
        echo "  <url>" >> sitemap.xml
        echo "    <loc>https://tools.skill2job.site/</loc>" >> sitemap.xml
        echo "    <priority>1.0</priority>" >> sitemap.xml
        echo "  </url>" >> sitemap.xml

        echo '</urlset>' >> sitemap.xml

    - name: Commit and push sitemap
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add sitemap.xml
        git commit -m "Auto-update sitemap.xml [skip ci]" || echo "No changes to commit"
        git push
